# Base plugin definition
refs:
    - python.yml    # Python path contribution
    #git.yml         # Git version/requirement
    - output.yml    # Output dir/clean
    - tasks.yml     # Meta tasks definition
